name: PlatformStats
description: A DWH data monitoring mobile app, built with Flutter.

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0
  flutter_sparkline: ^0.1.0
  flutter_staggered_grid_view: ^0.3.0
  charts_flutter: ^0.6.0
  cupertino_icons: ^0.1.2
  intl: ^0.15.8
  scoped_model: ^1.0.1
  path_provider: ^1.2.0
  flutter_local_notifications: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.2
  build_runner: ^1.6.2
  build_web_compilers: ^1.2.0

flutter_icons:
  android: true
  ios: "Example-Icon"
  image_path: "assets/analytics.png"
  image_path_android: "assets/analytics.png"
  image_path_ios: "assets/analytics.png"
  adaptive_icon_background: "#FFFAFAFA"
  adaptive_icon_foreground: "assets/analytics.png"

flutter:

  uses-material-design: true
  assets:
    - assets/

  # fonts:
  #   - family: Bitstream
  #     fonts:
  #       - asset: fonts/VeraMono.ttf
  #       - asset: fonts/VeraMoIt.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
